fleet_management/accounts/urls.py
from django.urls import path,include
from.import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup_view, name="signup"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
]

fleet_management/core/urls.py
from .import views
from django.urls import path

app_name = 'core'
urlpatterns = [
    path("list/", views.list_vehicles, name="list"),
    path("detail/<int:id>/", views.detail_view, name='vehicle_detail'),
    path("reserve/<int:id>/", views.reserve_vehicle , name='res'),
]

fleet_management/fleet_management/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('core/', include('core.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fleet_management/accounts/models.py
from django.db import models

# Create your models here.

fleet_management/core/models.py
from django.db import models
from django.contrib.auth.models import User


class Vehicle(models.Model):
    vehicle_name = models.CharField(max_length=100, null=True)
    vehicle_type = models.CharField(max_length=100)
    vehicle_description = models.TextField(max_length=255)
    vehicle_Pnumber = models.CharField(max_length=7)
    color = models.CharField(max_length=100,verbose_name="vehicle color",null=True)
    photo = models.ImageField(null=True)

    def __str__(self):
        return self.vehicle_name


class Reservation(models.Model):
    vehicle = models.ForeignKey(Vehicle, related_name='vehicle_id', on_delete=models.CASCADE)
    customer = models.ForeignKey(User, related_name='Customer_id', on_delete=models.CASCADE)
    rent_from = models.DateTimeField(verbose_name="date rented")
    rent_to = models.DateField(verbose_name="date returned")

class ReturnVehicle(models.Model):
    customer = models.ForeignKey(User, related_name='return_Customer_id', on_delete=models.CASCADE)
    vehicle = models.ForeignKey(Vehicle, related_name='return_vehicle_id', on_delete=models.CASCADE)
    DOR = models.DateField(verbose_name="date returned")
    condition = models.CharField(max_length=200)
    mileage = models.DecimalField(max_digits=5, decimal_places=2)

    def __str__(self):
        return self.mileage

fleet_management/core/forms.py
from django import forms
from .models import *

class DateInput(forms.DateInput):
    input_type = 'date'

class ReservationForm(forms.ModelForm):

    class Meta:
        model = Reservation
        fields = ['rent_from','rent_to',]
        widgets = {
            'rent_from': DateInput(),
            'rent_to': DateInput(),
        }

fleet_management/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

# Create your views here.
def signup_view(request):
    form = UserCreationForm()
    if request.method =='POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            #remember to log the user in
            login(request, user)
            return redirect('accounts:signup')
        else:
            form = UserCreationForm
    return render(request, 'accounts/signup.html', {'form': form})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            #log in the user
            user = form.get_user()
            login(request, user)
            return redirect('core:list')
    else:
        form = AuthenticationForm()
    return render(request, "accounts/login.html", {'form':form })

def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('accounts:signup')

fleet_management/core/views.py
from django.shortcuts import render, get_object_or_404,redirect
from django.views.generic.detail import DetailView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from .forms import *
from .models import *

@login_required
def list_vehicles(request):
    listx = Vehicle.objects.all()
    context ={"vehicles": listx}
    return render(request, "list_view.html", context)

@login_required
def reserve_vehicle(request, id):
    v = get_object_or_404(Vehicle, pk=id)
    if request.method == 'POST':
        form = ReservationForm(request.POST)
        if form.is_valid():
            form.save(commit=False)
            form.vehicle = v
            form.customer = User
            form.save()
            return redirect('core:list')
    else:
        form = ReservationForm()
        return redirect('core:list')

    return render(request, 'detail_view.html')

class VehicleDetailView(DetailView):
    template_name = 'detail_view.html'
    queryset = Vehicle.objects.all()

    def get_object(self):
        id_ = self.kwargs.get("id")
        return get_object_or_404(Vehicle, id=id_)

fleet_management/accounts/templates/accounts/login.html
{% extends 'templates/base.html' %}
{% block content %}
    <h1>Login</h1>
    <form class="site-form" action="{%url 'accounts:login' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Login">
    </form>
{% endblock %}

fleet_management/accounts/templates/accounts/signup.html
{% extends 'templates/base.html' %}

{% block content %}
    <h1>Signup</h1>
    <form class="site-form" action="." method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Signup">
    </form>
{% endblock %}

fleet_management/core/templates/detail_view.html
{% extends 'templates/base.html' %}

{% block content %}
    <h1>{{object.id}} : {{ object.vehicle_name }}</h1>
    <p>{{ object.vehicle_description }}</p>
    <img src="{{object.photo.url}}">
    <form method="POST" action="{% url 'core:res' object.id %}">
        {% csrf_token %}
        {{form}}
        <button type="submit" class="btn btn-success;">reserve</button>
    </form>
{% endblock %}

fleet_management/core/templates/list_view.html
{% extends 'templates/base.html' %}

{% block content %}
    {% for vehicle in vehicles %}
        <a href="{% url 'core:vehicle_detail' id=vehicle.id %}"><h1>{{ vehicle.vehicle_name }}</h1></a>
        <h3>{{ vehicle.vehicle_type }}</h3>
        <p>{{ vehicle.vehicle_Pnumber }}</p>
        <p>{{vehicle.color}}</p>
    {%endfor%}
{% endblock %}

fleet_management/templates/base.html
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <title>Django People</title>
  </head>
  <body>
  <nav>
      <ul>
          <li>
              <form class="logout-link" action="{%url 'accounts:logout'%}" method="post">
                  {% csrf_token %}
                  <button type="submit">Logout</button>
              </form>
          </li>
      </ul>
  </nav>
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-8">
          <hr class="mt-0 mb-4">
            <div style="align: left">
                {% if user.is_authenticated %}
                    <h4 class="mt-2">Welcome {{ user.username }}</h4>
                {% else %}
                    <a href="{% url django.contrib.auth.login %}">Login</a>
                    {% endif %}
            </div>
          {% block content %}
          {% endblock %}
        </div>
      </div>
    </div>
  </body>
</html>